import { IconTypes } from "./Icon"

const iconMap: Record<IconTypes, any> = {
  albumBold: require("../assets/albumBold.svg"),
  albumOutline: require("../assets/albumOutline.svg"),
  altArrowLeftOutline: require("../assets/altArrowLeftOutline.svg"),
  appleLogo: require("../assets/appleLogo.svg"),
  arrowRight: require("../assets/arrowRight.svg"),
  basketballBold: require("../assets/basketballBold.svg"),
  buildingsBold: require("../assets/buildingsBold.svg"),
  closeCircleBold: require("../assets/closeCircleBold.svg"),
  downloadBold: require("../assets/downloadBold.svg"),
  emojiFunnyCircleBold: require("../assets/emojiFunnyCircleBold.svg"),
  emptyMafoo: require("../assets/emptyMafoo.svg"),
  errorLogo: require("../assets/errorLogo.svg"),
  fireBold: require("../assets/fireBold.svg"),
  galleryAddOutline: require("../assets/galleryAddOutline.svg"),
  galleryIcon: require("../assets/galleryIcon.svg"),
  hamburger: require("../assets/hamburger.svg"),
  handShake: require("../assets/handShake.svg"),
  heartAngleBold: require("../assets/heartAngleBold.svg"),
  heartBold: require("../assets/heartBold.svg"),
  heartPink: require("../assets/heartPink.svg"),
  info: require("../assets/info.svg"),
  insta: require("../assets/insta.svg"),
  kakaoLogo: require("../assets/kakaoLogo.svg"),
  mafooLogo: require("../assets/mafooLogo.svg"),
  mafooLogo2025: require("../assets/mafooLogo2025.svg"),
  message: require("../assets/message.svg"),
  pen: require("../assets/pen.svg"),
  permission: require("../assets/permission.svg"),
  qrIcon: require("../assets/qrIcon.svg"),
  reelOutline: require("../assets/reelOutline.svg"),
  sadMafoo: require("../assets/sadMafoo.svg"),
  scannerOutline: require("../assets/scannerOutline.svg"),
  starFallMinimalisticBold: require("../assets/starFallMinimalisticBold.svg"),
  trash: require("../assets/trash.svg"),
  uploadMafoo: require("../assets/uploadMafoo.svg"),
  userCircleBold: require("../assets/userCircleBold.svg"),
  userCircleOutline: require("../assets/userCircleOutline.svg"),
  widgetAddOutline: require("../assets/widgetAddOutline.svg"),
  clapperBoardPlay: require("../assets/clapperBoardPlay.svg"),
  albumEditPencil: require("../assets/albumEditPencil.svg"),
  mafooCharacter1: require("../assets/mafooCharacter1.svg"),
  checkCircleBold: require("../assets/checkCircleBold.svg"),
  securityEye: require("../assets/securityEye.svg"),
  heartBoldMonoColor: require("../assets/heartBoldMonoColor.svg"),
  shareIcon: require("../assets/shareIcon.svg"),
  galleryImageIcon: require("../assets/galleryImageIcon.svg"),
  filledPen: require("../assets/filledPen.svg"),
  clipboardHeart: require("../assets/clipboardHeart.svg"),
  clipboardRemove: require("../assets/clipboardRemove.svg"),
  closeIcon: require("../assets/closeIcon.svg"),
}

export default iconMap
